{{ if eq .Values.protocol "https" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.tls.acme_server }}
    # Email address used for ACME registration
    email: {{ .Values.tls.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.tls.privateKeySecretRefName }}
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class:  nginx
{{ end }}